export const PLACE_ORDER_DATA = {
  totalAmount: 0,
  shopId: 0,
  deliveryAddress: "string",
  latitude: 0,
  longitude: 0,
  orderItems: [
    {
      id: 0,
      qty: 0,
      unitPrice: 0,
      flavor: "string",
      size: "string",
    },
  ],
  paymentMethod: "string",
  distance: 0,
  description: "string",
  customerId: "string",
  isPaid: true,
  deliveryFee: 0,
  statusId: 0,
  preferenceName: "string",
  preferenceId: 0,
  preferencePhone: "string",
};
